apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opensearch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
automountServiceAccountToken: false
