apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluvio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluvio.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
