apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluvio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluvio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
