apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluvio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluvio.labels" . | nindent 4 }}
automountServiceAccountToken: false
