apiVersion: v1
kind: Service
metadata:
  name: {{ include "pan-african-ekyc.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "pan-african-ekyc.name" . }}
