apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tigerbeetle.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tigerbeetle.labels" . | nindent 4 }}
automountServiceAccountToken: false
