apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakehouse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
