apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lakehouse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
automountServiceAccountToken: false
