apiVersion: v1
kind: Service
metadata:
  name: {{ include "lakehouse.fullname" . }}-trino
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: trino
spec:
  type: ClusterIP
  selector:
    {{- include "lakehouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: trino
  ports:
    - name: http
      port: 8080
      targetPort: 8080
