apiVersion: v1
kind: Service
metadata:
  name: {{ include "dapr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dapr.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
