apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dapr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dapr.labels" . | nindent 4 }}
automountServiceAccountToken: true
