apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apisix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apisix.labels" . | nindent 4 }}
automountServiceAccountToken: false
