apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: insure-pubsub
  namespace: insureportal
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "${KAFKA_BROKERS}"
    - name: authType
      value: "none"
    - name: consumerGroup
      value: "insureportal-dapr"
    - name: maxMessageBytes
      value: "1048576"
    - name: consumeRetryInterval
      value: "200ms"
