apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: insure-statestore
  namespace: insureportal
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "${DATABASE_URL}"
    - name: tableName
      value: "dapr_state"
    - name: keyPrefix
      value: "none"
    - name: cleanupIntervalInSeconds
      value: "3600"
