apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
automountServiceAccountToken: false
