/**
 * BillingAdminDashboard — Role-scoped KPI home screen for the Billing Admin Dashboard role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  Activity, AlertTriangle, CheckCircle, DollarSign, Receipt, RefreshCw, Scale, Settings, TrendingUp, XCircle
} from "lucide-react";

export default function BillingAdminDashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getBillingAdminKpi?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "Revenue (MTD ₦M)", value: kpi.revenueMtd ?? "—", icon: TrendingUp, trend: "up", trendValue: "↑ 11%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Unreconciled Items", value: kpi.unreconciledItems ?? "—", icon: AlertTriangle, trend: "down", trendValue: "↓ 4", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Platform Fees (MTD ₦)", value: kpi.platformFeesMtd ?? "—", icon: DollarSign, trend: "up", trendValue: "↑ 9%", status: "neutral" as const, href: "#", accent: "var(--role-billing-admin)" },
    { title: "Tenant Payouts (₦M)", value: kpi.tenantPayoutsMtd ?? "—", icon: Receipt, trend: "up", trendValue: "↑ 13%", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "Failed Transactions", value: kpi.failedTransactions ?? "—", icon: XCircle, trend: "down", trendValue: "↓ 2", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Disputes Open", value: kpi.disputesOpen ?? "—", icon: Scale, trend: "flat", trendValue: "stable", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "Chargeback Rate%", value: kpi.chargebackRate ?? "—", icon: Activity, trend: "down", trendValue: "↓ 0.2%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Reconciliation Rate%", value: kpi.reconciliationRate ?? "—", icon: CheckCircle, trend: "up", trendValue: "↑ 0.5%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-billing-admin)20", color: "var(--role-billing-admin)" }}
          >
            <Receipt size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              Billing Admin Dashboard
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              Ledger, Revenue & Reconciliation
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="Ledger"
              onClick={() => navigate("/billing-ledger")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-billing-admin)",
              }}
            >
              <Receipt size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Ledger
              </span>
            </button>
            <button
              key="Reconcile"
              onClick={() => navigate("/reconciliation")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <RefreshCw size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Reconcile
              </span>
            </button>
            <button
              key="Revenue"
              onClick={() => navigate("/revenue-analytics")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-low)",
              }}
            >
              <TrendingUp size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Revenue
              </span>
            </button>
            <button
              key="Settings"
              onClick={() => navigate("/billing-settings")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--text-secondary)",
              }}
            >
              <Settings size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Settings
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
