/**
 * BrokerDashboard — Role-scoped KPI home screen for the Broker Dashboard role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  BarChart2, Clock, DollarSign, FileText, PlusCircle, RefreshCw, TrendingUp, Users, XCircle
} from "lucide-react";

export default function BrokerDashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getBrokerKpi?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "Active Clients", value: kpi.activeClients ?? "—", icon: Users, trend: "up", trendValue: "+3 this wk", status: "neutral" as const, href: "#", accent: "var(--role-broker)" },
    { title: "Policies Written", value: kpi.policiesWritten ?? "—", icon: FileText, trend: "up", trendValue: "↑ 18%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Renewal Rate", value: kpi.renewalRate ?? "—", icon: RefreshCw, trend: "up", trendValue: "↑ 2.3%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Commission (MTD ₦)", value: kpi.commissionMtd ?? "—", icon: DollarSign, trend: "up", trendValue: "↑ 11%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Pending Quotes", value: kpi.pendingQuotes ?? "—", icon: Clock, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "Lapsed Policies", value: kpi.lapsedPolicies ?? "—", icon: XCircle, trend: "up", trendValue: "+2", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "GWP (MTD ₦M)", value: kpi.gwpMtd ?? "—", icon: TrendingUp, trend: "up", trendValue: "↑ 14%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Avg. Premium (₦)", value: kpi.avgPremium ?? "—", icon: BarChart2, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-broker)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-broker)20", color: "var(--role-broker)" }}
          >
            <Users size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              Broker Dashboard
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              Client Portfolio & Commissions
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="New Quote"
              onClick={() => navigate("/quote-engine")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-broker)",
              }}
            >
              <PlusCircle size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                New Quote
              </span>
            </button>
            <button
              key="Client List"
              onClick={() => navigate("/client-portfolio")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <Users size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Client List
              </span>
            </button>
            <button
              key="Commissions"
              onClick={() => navigate("/commission-management")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-low)",
              }}
            >
              <DollarSign size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Commissions
              </span>
            </button>
            <button
              key="Renewals"
              onClick={() => navigate("/policy-renewals")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--text-secondary)",
              }}
            >
              <RefreshCw size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Renewals
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
