/**
 * ClaimsDashboard — Role-scoped KPI home screen for the Claims Dashboard role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  Activity, AlertTriangle, CheckCircle, ClipboardList, Clock, DollarSign, PlusCircle, Scale
} from "lucide-react";

export default function ClaimsDashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getClaimsKpi?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "Open Claims", value: kpi.openClaims ?? "—", icon: ClipboardList, trend: "up", trendValue: "+5 today", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "FNOL Today", value: kpi.fnolToday ?? "—", icon: PlusCircle, trend: "up", trendValue: "+8", status: "neutral" as const, href: "#", accent: "var(--role-claims-adjuster)" },
    { title: "Avg. Settlement Days", value: kpi.avgSettlementDays ?? "—", icon: Clock, trend: "down", trendValue: "↓ 1.2d", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Settled Today", value: kpi.settledToday ?? "—", icon: CheckCircle, trend: "up", trendValue: "↑ 12%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Fraud Flags", value: kpi.fraudFlags ?? "—", icon: AlertTriangle, trend: "up", trendValue: "+2", status: "critical" as const, href: "#", accent: "var(--risk-critical)" },
    { title: "Disputed Claims", value: kpi.disputedClaims ?? "—", icon: Scale, trend: "flat", trendValue: "stable", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "Total Paid (MTD ₦M)", value: kpi.totalPaidMtd ?? "—", icon: DollarSign, trend: "up", trendValue: "↑ 9%", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "SLA Breach Rate", value: kpi.slaBreachRate ?? "—", icon: Activity, trend: "down", trendValue: "↓ 0.8%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-claims-adjuster)20", color: "var(--role-claims-adjuster)" }}
          >
            <ClipboardList size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              Claims Dashboard
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              FNOL, Adjudication & Settlement
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="New FNOL"
              onClick={() => navigate("/fnol-submission")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-claims-adjuster)",
              }}
            >
              <PlusCircle size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                New FNOL
              </span>
            </button>
            <button
              key="Claims Queue"
              onClick={() => navigate("/claims-management")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <ClipboardList size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Claims Queue
              </span>
            </button>
            <button
              key="Fraud Cases"
              onClick={() => navigate("/fraud-case-management")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-critical)",
              }}
            >
              <AlertTriangle size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Fraud Cases
              </span>
            </button>
            <button
              key="Settlements"
              onClick={() => navigate("/claims-settlement")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-low)",
              }}
            >
              <CheckCircle size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Settlements
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
