/**
 * ComplianceDashboard — Role-scoped KPI home screen for the Compliance Dashboard role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  AlertTriangle, BarChart2, BookOpen, ClipboardList, FileText, GraduationCap, Shield, UserCheck, XCircle
} from "lucide-react";

export default function ComplianceDashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getComplianceKpi?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "Open AML Alerts", value: kpi.openAmlAlerts ?? "—", icon: AlertTriangle, trend: "up", trendValue: "+4", status: "critical" as const, href: "#", accent: "var(--risk-critical)" },
    { title: "KYC Pending", value: kpi.kycPending ?? "—", icon: UserCheck, trend: "down", trendValue: "↓ 6", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "SAR Filed (MTD)", value: kpi.sarFiledMtd ?? "—", icon: FileText, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-compliance-officer)" },
    { title: "Sanctions Hits", value: kpi.sanctionsHits ?? "—", icon: XCircle, trend: "flat", trendValue: "0 new", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Policy Violations", value: kpi.policyViolations ?? "—", icon: Shield, trend: "down", trendValue: "↓ 2", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Audit Items Open", value: kpi.auditItemsOpen ?? "—", icon: ClipboardList, trend: "up", trendValue: "+7", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "Training Compliance%", value: kpi.trainingCompliance ?? "—", icon: GraduationCap, trend: "up", trendValue: "↑ 3%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Regulatory Filings", value: kpi.regulatoryFilings ?? "—", icon: BookOpen, trend: "flat", trendValue: "on track", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-compliance-officer)20", color: "var(--role-compliance-officer)" }}
          >
            <Shield size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              Compliance Dashboard
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              AML/KYC, Audit & Regulatory
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="AML/KYC"
              onClick={() => navigate("/aml-kyc-management")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-compliance-officer)",
              }}
            >
              <Shield size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                AML/KYC
              </span>
            </button>
            <button
              key="Audit Trail"
              onClick={() => navigate("/audit-trail")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <BookOpen size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Audit Trail
              </span>
            </button>
            <button
              key="Compliance Rpts"
              onClick={() => navigate("/compliance-reporting")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-low)",
              }}
            >
              <BarChart2 size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Compliance Rpts
              </span>
            </button>
            <button
              key="Alerts"
              onClick={() => navigate("/compliance-alerts")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-critical)",
              }}
            >
              <AlertTriangle size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Alerts
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
