/**
 * Ifrs17Dashboard — Role-scoped KPI home screen for the IFRS 17 Dashboard role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  Activity, AlertTriangle, BarChart2, BookOpen, DollarSign, Receipt, Shield, TrendingUp
} from "lucide-react";

export default function Ifrs17Dashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getIfrs17Dashboard?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "BEL (₦M)", value: kpi.bel ?? "—", icon: TrendingUp, trend: "up", trendValue: "↑ 2.1%", status: "neutral" as const, href: "#", accent: "var(--role-actuary)" },
    { title: "Risk Adjustment (₦M)", value: kpi.riskAdjustment ?? "—", icon: Shield, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-actuary)" },
    { title: "CSM (₦M)", value: kpi.csm ?? "—", icon: DollarSign, trend: "up", trendValue: "↑ 1.4%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Loss Component (₦M)", value: kpi.lossComponent ?? "—", icon: AlertTriangle, trend: "down", trendValue: "↓ 0.8%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Insurance Revenue (₦M)", value: kpi.insuranceRevenue ?? "—", icon: BarChart2, trend: "up", trendValue: "↑ 5.2%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Insurance Service Exp", value: kpi.insuranceServiceExp ?? "—", icon: Receipt, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "Net Financial Result", value: kpi.netFinancialResult ?? "—", icon: Activity, trend: "up", trendValue: "↑ 3.1%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Discount Rate%", value: kpi.discountRate ?? "—", icon: TrendingUp, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-actuary)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-actuary)20", color: "var(--role-actuary)" }}
          >
            <BookOpen size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              IFRS 17 Dashboard
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              Insurance Contract Accounting
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="Run Calc"
              onClick={() => navigate("/reserve-calculations")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-actuary)",
              }}
            >
              <TrendingUp size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Run Calc
              </span>
            </button>
            <button
              key="GMM Model"
              onClick={() => navigate("/actuarial-models")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <BookOpen size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                GMM Model
              </span>
            </button>
            <button
              key="PAA Model"
              onClick={() => navigate("/actuarial-models")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-low)",
              }}
            >
              <Activity size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                PAA Model
              </span>
            </button>
            <button
              key="Reports"
              onClick={() => navigate("/actuarial-reports")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--text-secondary)",
              }}
            >
              <BarChart2 size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Reports
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
