/**
 * PolicyholderDashboard — Role-scoped KPI home screen for the My Insurance role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  BookOpen, Calendar, CheckCircle, ClipboardList, DollarSign, FileText, Home, PlusCircle, RefreshCw, Shield, Star
} from "lucide-react";

export default function PolicyholderDashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getPolicyholderKpi?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "Active Policies", value: kpi.activePolicies ?? "—", icon: FileText, trend: "flat", trendValue: "stable", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Open Claims", value: kpi.openClaims ?? "—", icon: ClipboardList, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-policyholder)" },
    { title: "Next Premium Due", value: kpi.nextPremiumDue ?? "—", icon: Calendar, trend: undefined, trendValue: undefined, status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "Total Coverage (₦M)", value: kpi.totalCoverage ?? "—", icon: Shield, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "Upcoming Renewals", value: kpi.upcomingRenewals ?? "—", icon: RefreshCw, trend: "up", trendValue: "+1", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "Paid Premiums (YTD ₦)", value: kpi.paidPremiumsYtd ?? "—", icon: DollarSign, trend: "up", trendValue: "↑ 8%", status: "neutral" as const, href: "#", accent: "var(--role-policyholder)" },
    { title: "Claim Paid (YTD ₦)", value: kpi.claimPaidYtd ?? "—", icon: CheckCircle, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Loyalty Points", value: kpi.loyaltyPoints ?? "—", icon: Star, trend: "up", trendValue: "+120", status: "good" as const, href: "#", accent: "var(--risk-low)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-policyholder)20", color: "var(--role-policyholder)" }}
          >
            <Home size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              My Insurance
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              Policies, Claims & Payments
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="File a Claim"
              onClick={() => navigate("/my-claims")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-policyholder)",
              }}
            >
              <PlusCircle size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                File a Claim
              </span>
            </button>
            <button
              key="Pay Premium"
              onClick={() => navigate("/premium-payment")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <DollarSign size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Pay Premium
              </span>
            </button>
            <button
              key="My Policies"
              onClick={() => navigate("/my-policies")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-low)",
              }}
            >
              <FileText size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                My Policies
              </span>
            </button>
            <button
              key="Documents"
              onClick={() => navigate("/my-documents")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--text-secondary)",
              }}
            >
              <BookOpen size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Documents
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
