/**
 * RegulatorDashboard — Role-scoped KPI home screen for the Regulatory Dashboard role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  Activity, AlertTriangle, BarChart2, BookOpen, Building2, DollarSign, FileText, Landmark, Scale, Search, TrendingUp
} from "lucide-react";

export default function RegulatorDashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getRegulatorKpi?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "Licensed Insurers", value: kpi.licensedInsurers ?? "—", icon: Building2, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-regulator)" },
    { title: "Solvency Ratio Avg%", value: kpi.solvencyRatioAvg ?? "—", icon: TrendingUp, trend: "up", trendValue: "↑ 1.2%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Complaints (MTD)", value: kpi.complaintsMtd ?? "—", icon: AlertTriangle, trend: "down", trendValue: "↓ 8%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Pending Filings", value: kpi.pendingFilings ?? "—", icon: FileText, trend: "up", trendValue: "+3", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "Market GWP (₦B)", value: kpi.marketGwp ?? "—", icon: DollarSign, trend: "up", trendValue: "↑ 6.4%", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "Claims Ratio Avg%", value: kpi.claimsRatioAvg ?? "—", icon: BarChart2, trend: "down", trendValue: "↓ 1.1%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Enforcement Actions", value: kpi.enforcementActions ?? "—", icon: Scale, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-regulator)" },
    { title: "Market Concentration", value: kpi.marketConcentration ?? "—", icon: Activity, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-regulator)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-regulator)20", color: "var(--role-regulator)" }}
          >
            <Landmark size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              Regulatory Dashboard
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              NAICOM/CBN Oversight — Read Only
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="Market Reports"
              onClick={() => navigate("/regulatory-reports")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-regulator)",
              }}
            >
              <BarChart2 size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Market Reports
              </span>
            </button>
            <button
              key="Solvency Data"
              onClick={() => navigate("/solvency-reporting")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <TrendingUp size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Solvency Data
              </span>
            </button>
            <button
              key="Audit Access"
              onClick={() => navigate("/regulatory-audit")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-low)",
              }}
            >
              <BookOpen size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Audit Access
              </span>
            </button>
            <button
              key="Search"
              onClick={() => navigate("/regulatory-search")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--text-secondary)",
              }}
            >
              <Search size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Search
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
