/**
 * ReinsurerDashboard — Role-scoped KPI home screen for the Reinsurance Dashboard role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  Activity, BarChart2, ClipboardList, Clock, DollarSign, Scale, Shield, TrendingUp
} from "lucide-react";

export default function ReinsurerDashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getReinsurerKpi?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "Active Treaties", value: kpi.activeTreaties ?? "—", icon: Scale, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-reinsurer)" },
    { title: "Ceded Premium (MTD ₦M)", value: kpi.cedingPremiumMtd ?? "—", icon: DollarSign, trend: "up", trendValue: "↑ 7%", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "Recoveries (MTD ₦M)", value: kpi.recoveriesMtd ?? "—", icon: TrendingUp, trend: "up", trendValue: "↑ 4%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Open RI Claims", value: kpi.openRiClaims ?? "—", icon: ClipboardList, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-reinsurer)" },
    { title: "Treaty Utilization%", value: kpi.treatyUtilization ?? "—", icon: Activity, trend: "up", trendValue: "↑ 2.1%", status: "neutral" as const, href: "#", accent: "var(--role-reinsurer)" },
    { title: "Net Retention (₦M)", value: kpi.netRetention ?? "—", icon: Shield, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "Loss Ratio (RI)", value: kpi.lossRatioRi ?? "—", icon: BarChart2, trend: "down", trendValue: "↓ 1.8%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Pending Settlements", value: kpi.pendingSettlements ?? "—", icon: Clock, trend: "flat", trendValue: "stable", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-reinsurer)20", color: "var(--role-reinsurer)" }}
          >
            <Scale size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              Reinsurance Dashboard
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              Treaties, Premiums & Claims
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="Treaties"
              onClick={() => navigate("/reinsurance-treaties")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-reinsurer)",
              }}
            >
              <Scale size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Treaties
              </span>
            </button>
            <button
              key="RI Claims"
              onClick={() => navigate("/reinsurance-claims")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <ClipboardList size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                RI Claims
              </span>
            </button>
            <button
              key="Premiums"
              onClick={() => navigate("/reinsurance-premiums")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-low)",
              }}
            >
              <DollarSign size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Premiums
              </span>
            </button>
            <button
              key="RI Reports"
              onClick={() => navigate("/reinsurance-reports")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--text-secondary)",
              }}
            >
              <BarChart2 size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                RI Reports
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
