/**
 * SupervisorDashboard — Role-scoped KPI home screen for the Supervisor Dashboard role.
 * Auto-generated by scripts/generate_role_dashboards.py
 */
import { trpc } from "@/_core/trpc";
import { KpiCard } from "@/components/insurance/KpiCard";
import { useIsMobile } from "@/hooks/useMobile";
import { useLocation } from "wouter";
import {
  Activity, AlertTriangle, ArrowRightLeft, BarChart2, Clock, DollarSign, TrendingUp, Users, Wallet
} from "lucide-react";

export default function SupervisorDashboard() {
  const isMobile = useIsMobile();
  const [, navigate] = useLocation();
  const { data, isLoading } = (trpc as any).insuranceKpiDashboard?.getSupervisorKpi?.useQuery?.() ?? { data: null, isLoading: false };
  const kpi = data?.kpis ?? {};

  const cards = [
    { title: "Active Agents", value: kpi.activeAgents ?? "—", icon: Users, trend: "flat", trendValue: "stable", status: "neutral" as const, href: "#", accent: "var(--role-supervisor)" },
    { title: "Transactions Today", value: kpi.transactionsToday ?? "—", icon: ArrowRightLeft, trend: "up", trendValue: "↑ 8%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Float Utilization%", value: kpi.floatUtilization ?? "—", icon: Wallet, trend: "up", trendValue: "↑ 3%", status: "neutral" as const, href: "#", accent: "var(--insurance-primary)" },
    { title: "SLA Breaches", value: kpi.slaBreaches ?? "—", icon: AlertTriangle, trend: "down", trendValue: "↓ 1", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Pending Approvals", value: kpi.pendingApprovals ?? "—", icon: Clock, trend: "up", trendValue: "+6", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "Revenue (Today ₦)", value: kpi.revenueToday ?? "—", icon: DollarSign, trend: "up", trendValue: "↑ 12%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
    { title: "Escalations Open", value: kpi.escalationsOpen ?? "—", icon: AlertTriangle, trend: "flat", trendValue: "stable", status: "warning" as const, href: "#", accent: "var(--risk-medium)" },
    { title: "Agent Performance%", value: kpi.agentPerformance ?? "—", icon: TrendingUp, trend: "up", trendValue: "↑ 2.1%", status: "good" as const, href: "#", accent: "var(--risk-low)" },
  ];

  return (
    <div
      className="min-h-screen"
      style={{
        background: "var(--page-bg)",
        paddingBottom: isMobile ? "calc(4rem + var(--safe-area-bottom))" : "2rem",
      }}
    >
      {/* Header */}
      <div
        className="sticky top-0 z-10 px-4 py-3 flex items-center justify-between"
        style={{
          background: "var(--header-bg)",
          borderBottom: "1px solid var(--card-border)",
          backdropFilter: "blur(12px)",
        }}
      >
        <div className="flex items-center gap-3">
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: "var(--role-supervisor)20", color: "var(--role-supervisor)" }}
          >
            <Activity size={18} />
          </span>
          <div>
            <h1 className="text-base font-semibold" style={{ color: "var(--text-primary)" }}>
              Supervisor Dashboard
            </h1>
            <p className="text-xs" style={{ color: "var(--text-secondary)" }}>
              Agent Oversight & Operations
            </p>
          </div>
        </div>
      </div>

      <div className="px-4 pt-4 space-y-6">
        {/* KPI Grid */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Key Metrics
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            {cards.map((c) => (
              <KpiCard
                key={c.title}
                title={c.title}
                value={c.value}
                icon={c.icon}
                trend={c.trend}
                trendValue={c.trendValue}
                subtitle={c.subtitle}
                status={c.status}
                accentColor={c.accent}
                loading={isLoading}
                onClick={() => navigate(c.href)}
              />
            ))}
          </div>
        </section>

        {/* Quick Actions */}
        <section>
          <h2 className="text-xs font-semibold uppercase tracking-wide mb-3"
              style={{ color: "var(--text-secondary)" }}>
            Quick Actions
          </h2>
          <div className={`grid gap-3 ${isMobile ? "grid-cols-2" : "grid-cols-4"}`}>
            <button
              key="Agent Mgmt"
              onClick={() => navigate("/agent-management")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--role-supervisor)",
              }}
            >
              <Users size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Agent Mgmt
              </span>
            </button>
            <button
              key="Float Mgmt"
              onClick={() => navigate("/float-management")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--insurance-primary)",
              }}
            >
              <Wallet size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Float Mgmt
              </span>
            </button>
            <button
              key="SLA Monitor"
              onClick={() => navigate("/sla-monitoring")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--risk-medium)",
              }}
            >
              <Activity size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                SLA Monitor
              </span>
            </button>
            <button
              key="Reports"
              onClick={() => navigate("/analytics-dashboard")}
              className="flex flex-col items-center justify-center gap-2 p-4 rounded-xl
                         transition-all duration-150 hover:shadow-md hover:-translate-y-0.5"
              style={{
                background: "var(--card-bg)",
                border: "1px solid var(--card-border)",
                color: "var(--text-secondary)",
              }}
            >
              <BarChart2 size={22} />
              <span className="text-xs font-medium text-center leading-tight"
                    style={{ color: "var(--text-primary)" }}>
                Reports
              </span>
            </button>
          </div>
        </section>
      </div>
    </div>
  );
}
