/*
gen-manifest — 54Link POS Installer Build Tool
================================================
Computes SHA-256 checksums for all embedded service binaries and prints
the Go source snippet that should replace the integrityManifest variable
in cmd/installer/main.go.

Usage (from the installer/ directory):
  go run ./scripts/gen-manifest/main.go

Output is printed to stdout. Paste it into main.go to lock the checksums.

Typical CI workflow:
  1. Build the three service binaries (resilience-agent, offline-queue, analytics-service)
  2. Copy them into installer/cmd/installer/embedded/
  3. Run this script to generate the manifest
  4. Paste the output into main.go
  5. Build the installer: go build -o bin/54link-installer ./cmd/installer/
*/

package main

import (
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"fmt"
	"log"
	"os"
	"path/filepath"

	_ "github.com/lib/pq"
)

var embeddedBinaries = []string{
	"embedded/resilience-agent",
	"embedded/offline-queue",
	"embedded/analytics-service",
}

var db *sql.DB

func initDB() {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "postgresql://ngapp:ngapp@localhost:5432/ngapp?sslmode=disable"
	}
	var err error
	db, err = sql.Open("postgres", dsn)
	if err != nil {
		log.Printf("WARN: database connection failed: %v (running in degraded mode)", err)
		return
	}
	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(5)
	if err = db.Ping(); err != nil {
		log.Printf("WARN: database ping failed: %v (running in degraded mode)", err)
		db = nil
		return
	}
	log.Printf("Connected to PostgreSQL for installer")

	// Create table if not exists
	_, err = db.Exec(`CREATE TABLE IF NOT EXISTS installer (
		id SERIAL PRIMARY KEY,
		data JSONB NOT NULL DEFAULT '{}',
		status VARCHAR(50) DEFAULT 'active',
		created_at TIMESTAMPTZ DEFAULT NOW(),
		updated_at TIMESTAMPTZ DEFAULT NOW(),
		tenant_id INTEGER DEFAULT 1
	)`)
	if err != nil {
		log.Printf("WARN: table creation failed: %v", err)
	}
}

func main() {
	initDB()
	if db != nil {
		defer func() { _ = db.Close() }()
	}
	// Determine the embedded dir relative to this script
	// When run as `go run ./scripts/gen-manifest/main.go` from installer/,
	// the working directory is installer/
	// The binaries live in installer/cmd/installer/embedded/
	baseDir := filepath.Join("cmd", "installer")

	fmt.Println("// integrityManifest — generated by scripts/gen-manifest/main.go")
	fmt.Println("// DO NOT EDIT MANUALLY")
	fmt.Println("var integrityManifest = map[string]string{")

	allOK := true
	for _, rel := range embeddedBinaries {
		fullPath := filepath.Join(baseDir, rel)
		data, err := os.ReadFile(fullPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "WARNING: cannot read %s: %v (using placeholder)\n", fullPath, err)
			fmt.Printf("\t%q: %q, // MISSING — build pipeline must supply this binary\n", rel, "")
			allOK = false
			continue
		}
		sum := sha256.Sum256(data)
		hash := hex.EncodeToString(sum[:])
		fmt.Printf("\t%q: %q,\n", rel, hash)
	}

	fmt.Println("}")

	if !allOK {
		fmt.Fprintln(os.Stderr, "\n⚠️  Some binaries were missing. Placeholders were used.")
		fmt.Fprintln(os.Stderr, "   Ensure all binaries are present before building a production installer.")
		os.Exit(1)
	}
}
