/**
 * pbacScanner.integration.test.ts — Wave-2a (B1 + B2) integration coverage
 * against the REAL PG (PGlite) schema.
 *
 * B1 (PBAC): the policy store is seeded by parsing the REAL in-repo Permify
 * schema file (infra/permify/schema.perm) — no mocks anywhere. The ONLY
 * boundary stub is Permify itself: the integration environment has no
 * Permify container, so PERMIFY_URL points at a dead port
 * (vitest.integration.config.ts) and the transport fails for real. The
 * fail-closed case (PRECONDITION_FAILED, honest error) and the explicitly
 * labelled PERMIFY_FAIL_OPEN degraded case are both exercised against that
 * real failing transport — the Permify answer path is covered by the
 * production deployment, not fabricatable here (LABELLED transport gap).
 *
 * B2 (scanner): availability-probe tests + the fail-loud no-scanner case
 * (PATH pointed at an empty dir — a REAL probe outcome, not a mock) + a
 * parser test against REAL captured trivy JSON fixtures
 * (tests/fixtures/trivy-*.json.golden — real trivy output, provenance noted
 * at the fixture constants below) + a store
 * round-trip through the real recorder functions.
 *
 * This is the only suite file that reads/writes pbac_policies,
 * pbac_access_evaluations, security_scan_runs and security_scan_findings
 * (grep-verified), so the fail-loud empty-store cases run FIRST.
 */
import { readFileSync } from "fs";
import path from "path";
import { describe, it, beforeAll, afterAll } from "vitest";

import { getDb } from "../../server/db";
import {
  listPolicies,
  loadPermifySchema,
  parsePermifySchema,
  syncPoliciesFromSchema,
} from "../../server/lib/pbacPolicies";
import {
  insertFindings,
  listScanFindings,
  listScanRuns,
  parseTrivyJson,
  probeScanners,
  recordRunFinish,
  recordRunStart,
  selectScanner,
  severityCounts,
} from "../../server/lib/securityScanner";
import {
  callerFor,
  adminUser,
  expectCounted as expect,
  expectTrpcError,
  resetAssertionCount,
  getAssertionCount,
} from "./helpers/trpc";

const FILE = "pbacScanner";
// REAL trivy `--format json` captures (NOT invented): these are the
// aquasecurity/trivy v0.58.2 integration-testdata golden files, generated by
// real trivy runs upstream (the sandbox has no network path to run trivy's
// own vulnerability-DB update, so the tool's own published real outputs are
// used). Provenance:
//   github.com/aquasecurity/trivy@v0.58.2 integration/testdata/busybox-with-lockfile.json.golden
//   github.com/aquasecurity/trivy@v0.58.2 integration/testdata/secrets.json.golden
const TRIVY_VULN_FIXTURE = path.resolve(
  import.meta.dirname,
  "../fixtures/trivy-busybox-with-lockfile.json.golden"
);
const TRIVY_SECRET_FIXTURE = path.resolve(
  import.meta.dirname,
  "../fixtures/trivy-secrets.json.golden"
);

describe(`${FILE}: PBAC viewer + security scanner (B1, B2)`, () => {
  beforeAll(() => {
    resetAssertionCount();
  });

  afterAll(() => {
    console.log(`[${FILE}] assertions: ${getAssertionCount()}`);
  });

  // ── B1: policy store ──────────────────────────────────────────────────────

  it("getPolicies fails loud PRECONDITION_FAILED while the store is empty", async () => {
    const admin = callerFor(adminUser);
    const err = await expectTrpcError(
      admin.securityAudit.getPolicies({}),
      "PRECONDITION_FAILED"
    );
    expect(err.message).toContain("pbac_policies store is empty");
    expect(err.message).toContain("syncPbacPolicies");
  });

  it("parser extracts the real policies from the real schema file", () => {
    const { version, policies } = loadPermifySchema();
    expect(version).toBe("3.0.0");
    // The real v3.0.0 schema declares exactly 119 action statements across
    // 15 entities (enumerated 2026-09-12 by running this parser over the
    // file and printing every entity-action pair; 117 unique
    // (entity, permission) pairs — two pairs are declared twice in the
    // real file, see the sync test below).
    expect(policies.length).toBe(119);
    const manageTenant = policies.find(
      p => p.entity === "tenant" && p.permission === "manage_tenant"
    );
    expect(manageTenant?.expression).toBe("super_admin or admin");
  });

  it("parser fails loud on empty/garbage schema text", () => {
    expect(() => parsePermifySchema("// nothing here\n")).toThrow(
      /parsed 0 policies/
    );
  });

  it("syncPbacPolicies seeds the store from the real file; re-sync is idempotent", async () => {
    const admin = callerFor(adminUser);
    const first = await admin.securityAudit.syncPbacPolicies();
    expect(first.schemaVersion).toBe("3.0.0");
    // Known answers derived 2026-09-12 by running the REAL parser over
    // infra/permify/schema.perm v3.0.0 and enumerating the output: the file
    // contains 119 action declarations across 15 entities, but TWO
    // (entity, permission) pairs are declared TWICE in the real file —
    // tenant.view_tenant (two different grant expressions) and agent.view
    // ('supervisor' vs 'tenant.supervisor', textually different) — so the
    // upsert store keys on 117 UNIQUE policies: first sync inserts 117 rows
    // and updates 2 (the duplicate declarations), never dropping anything.
    expect(first.parsed).toBe(119);
    expect(first.inserted).toBe(117);
    expect(first.updated).toBe(2);

    const second = await admin.securityAudit.syncPbacPolicies();
    // Re-sync is idempotent: all 119 declarations now match existing rows.
    expect(second.inserted).toBe(0);
    expect(second.updated).toBe(second.parsed);

    const rows = await admin.securityAudit.getPolicies({ limit: 500 });
    // 117 unique (entity, permission) policies — the store key.
    expect(rows.length).toBe(117);
    const claimAdjudicate = rows.find(
      r => r.entity === "claim" && r.permission === "adjudicate"
    );
    expect(claimAdjudicate?.permifySchemaVersion).toBe("3.0.0");
    expect(claimAdjudicate?.expression).toContain("claims_adjuster");
  });

  // ── B1: access evaluation (LABELLED Permify-transport boundary) ───────────

  it("evaluateAccess fails closed with the honest error when Permify is unreachable", async () => {
    const admin = callerFor(adminUser);
    const prev = process.env.PERMIFY_FAIL_OPEN;
    // Fail-closed default: no insecure opt-in. The dead PERMIFY_URL
    // (127.0.0.1:9 from the integration env) makes the transport fail for
    // real — this is the honest production outcome without Permify.
    process.env.PERMIFY_FAIL_OPEN = "false";
    try {
      const err = await expectTrpcError(
        admin.securityAudit.evaluateAccess({
          subjectType: "user",
          subjectId: "91001",
          entityType: "claim",
          entityId: "CLM-1",
          permission: "view",
        }),
        "PRECONDITION_FAILED"
      );
      expect(err.message).toContain("Permify is unreachable");
    } finally {
      process.env.PERMIFY_FAIL_OPEN = prev;
    }
  });

  it("evaluateAccess honours PERMIFY_FAIL_OPEN as a labelled degraded verdict and logs it", async () => {
    const admin = callerFor(adminUser);
    // Integration env sets PERMIFY_FAIL_OPEN=true (same opt-in semantics as
    // _core/permify.ts): the verdict is allowed + source='permify_fail_open'.
    const result = await admin.securityAudit.evaluateAccess({
      subjectType: "user",
      subjectId: "91001",
      entityType: "policy",
      entityId: "POL-1",
      permission: "view",
    });
    expect(result.allowed).toBe(true);
    expect(result.source).toBe("permify_fail_open");
    expect(result.degraded).toBe(true);

    const log = await admin.securityAudit.getAccessEvaluations({ limit: 10 });
    const row = log.find(r => r.id === result.evaluationId);
    expect(row?.entityType).toBe("policy");
    expect(row?.permission).toBe("view");
    expect(row?.source).toBe("permify_fail_open");
  });

  // ── B2: scanner availability probing + fail-loud ─────────────────────────

  it("probeScanners reports exactly what it probed", () => {
    const report = probeScanners();
    expect(report.probes.map(p => p.scanner).sort()).toEqual([
      "semgrep",
      "trivy",
    ]);
    for (const p of report.probes) {
      // Every probe carries either a real version string or the exact
      // reason the binary could not be launched — never silence.
      expect(p.available ? p.version != null : p.error != null).toBe(true);
    }
  });

  it("runSecurityScan fails loud PRECONDITION_FAILED listing the probes when no scanner exists", async () => {
    const admin = callerFor(adminUser);
    const prevPath = process.env.PATH;
    // Point PATH at an empty dir: the trivy/semgrep PATH probes then fail
    // FOR REAL (ENOENT), exactly as on a host with no scanner installed.
    process.env.PATH = path.resolve(import.meta.dirname, "helpers");
    try {
      const report = probeScanners();
      expect(selectScanner(report)).toBeNull();
      expect(report.probes.every(p => !p.available)).toBe(true);
      const err = await expectTrpcError(
        admin.securityAudit.runSecurityScan({}),
        "PRECONDITION_FAILED"
      );
      expect(err.message).toContain("no security scanner is available");
      expect(err.message).toContain("trivy");
      expect(err.message).toContain("semgrep");
      expect(err.message).toContain("No scan was run");
    } finally {
      process.env.PATH = prevPath;
    }
  });

  // ── B2: parser against a REAL captured trivy fixture ─────────────────────

  it("parseTrivyJson parses real trivy output with exact known answers", () => {
    // Known answers read directly from the REAL captured outputs.
    const vulnFindings = parseTrivyJson(
      readFileSync(TRIVY_VULN_FIXTURE, "utf-8")
    );
    expect(vulnFindings.length).toBe(2);
    const counts = severityCounts(vulnFindings);
    expect(
      counts.CRITICAL + counts.HIGH + counts.MEDIUM + counts.LOW + counts.UNKNOWN
    ).toBe(vulnFindings.length);
    const anchor = vulnFindings.find(f => f.ruleId === "CVE-2019-15542");
    expect(anchor).toBeDefined();
    expect(anchor?.findingType).toBe("vulnerability");
    expect(anchor?.severity).toBe("HIGH");
    expect(anchor?.packageName).toBe("ammonia");
    expect(anchor?.installedVersion).toBe("1.9.0");
    expect(anchor?.fixedVersion).toBe(">= 2.1.0");
    expect(anchor?.target).toBe("Cargo.lock");

    const secretFindings = parseTrivyJson(
      readFileSync(TRIVY_SECRET_FIXTURE, "utf-8")
    );
    expect(secretFindings.length).toBe(2);
    const secret = secretFindings.find(f => f.ruleId === "aws-access-key-id");
    expect(secret?.findingType).toBe("secret");
    expect(secret?.severity).toBe("CRITICAL");
    expect(secret?.target).toBe("deploy.sh");
  });

  it("parseTrivyJson fails loud on non-trivy payloads", () => {
    expect(() => parseTrivyJson("not json at all")).toThrow(/not valid JSON/);
    expect(() => parseTrivyJson('{"foo": 1}')).toThrow(/no 'Results' key/);
  });

  // ── B2: run/finding store round-trip ──────────────────────────────────────

  it("run store records a real run lifecycle; history/findings queries read it back", async () => {
    const db = (await getDb())!;
    const admin = callerFor(adminUser);
    const fixtureFindings = [
      ...parseTrivyJson(readFileSync(TRIVY_VULN_FIXTURE, "utf-8")),
      ...parseTrivyJson(readFileSync(TRIVY_SECRET_FIXTURE, "utf-8")),
    ];

    const run = await recordRunStart(db, {
      scanner: "trivy",
      scannerVersion: "integration-test",
      targetPath: "/integration/target",
      startedAt: new Date("2020-06-01T10:00:00.000Z"),
      triggeredBy: adminUser.id,
    });
    expect(run.status).toBe("running");
    const inserted = await insertFindings(db, run.id, fixtureFindings);
    expect(inserted).toBe(fixtureFindings.length);
    const counts = severityCounts(fixtureFindings);
    await recordRunFinish(db, run.id, {
      finishedAt: new Date("2020-06-01T10:01:00.000Z"),
      status: "completed",
      totalFindings: fixtureFindings.length,
      severityCounts: counts,
    });

    const history = await admin.securityAudit.getSecurityScanHistory({});
    const histRow = history.data.find(r => r.id === run.id);
    expect(histRow?.status).toBe("completed");
    expect(histRow?.totalFindings).toBe(fixtureFindings.length);

    const found = await admin.securityAudit.getSecurityScanFindings({
      runId: run.id,
      limit: 500,
    });
    expect(found.total).toBe(fixtureFindings.length);
    const criticalOnly = await admin.securityAudit.getSecurityScanFindings({
      runId: run.id,
      severity: "CRITICAL",
    });
    expect(criticalOnly.total).toBe(counts.CRITICAL);
    expect(
      criticalOnly.data.every(f => f.severity === "CRITICAL")
    ).toBe(true);
  });
});
