module.exports = {
  apps: [{
    name: 'insureportal',
    script: 'server.cjs',
    instances: 'max',
    exec_mode: 'cluster',
    env: {
      NODE_ENV: 'production',
      PORT: 5002,
    },
    max_memory_restart: '500M',
    error_file: './logs/error.log',
    out_file: './logs/out.log',
    log_file: './logs/combined.log',
    time: true,
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    max_restarts: 10,
    restart_delay: 5000,
    watch: false,
    kill_timeout: 10000,
    listen_timeout: 10000,
    shutdown_with_message: true,
  }],
};
