export const UNAUTHED_ERR_MSG = "UNAUTHORIZED";
export const NOT_ADMIN_ERR_MSG = "FORBIDDEN: Admin role required";
export const NOT_FOUND_ERR_MSG = "NOT_FOUND";
export const FORBIDDEN_ERR_MSG = "FORBIDDEN";
export const COOKIE_NAME = "insureportal_session";
export const ONE_YEAR_MS = 365 * 24 * 60 * 60 * 1000;
export const ONE_DAY_MS = 24 * 60 * 60 * 1000;
export const ONE_HOUR_MS = 60 * 60 * 1000;
export const AXIOS_TIMEOUT_MS = 30_000;
export const MAX_FILE_SIZE_MB = 10;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;
export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;
export const MIN_PASSWORD_LENGTH = 8;
export const SESSION_DURATION_MS = 8 * ONE_HOUR_MS;
export const REFRESH_TOKEN_DURATION_MS = 30 * ONE_DAY_MS;
export const OTP_EXPIRY_MS = 10 * 60 * 1000; // 10 minutes
export const MAX_LOGIN_ATTEMPTS = 5;
export const LOCKOUT_DURATION_MS = 30 * 60 * 1000; // 30 minutes
export const FLOAT_PRECISION = 2;
export const CURRENCY_DEFAULT = "NGN";
export const PLATFORM_NAME = "InsurePortal";
export const SUPPORT_EMAIL = "support@insureportal.ng";
export const API_VERSION = "v1";
