apiVersion: v1
kind: Service
metadata:
  name: insureportal
  namespace: insureportal
  labels:
    app: insureportal
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5002
      protocol: TCP
      name: http
  selector:
    app: insureportal
---
apiVersion: v1
kind: Service
metadata:
  name: insureportal-metrics
  namespace: insureportal
  labels:
    app: insureportal
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: metrics
  selector:
    app: insureportal
