apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: insureportal-pubsub
  namespace: insureportal
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: consumerGroup
      value: "insureportal-dapr"
    - name: authType
      value: "none"
    - name: maxMessageBytes
      value: "1048576"
    - name: consumeRetryInterval
      value: "1000ms"
    - name: version
      value: "3.6.0"
