apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: insureportal-statestore
  namespace: insureportal
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis:6379"
    - name: redisPassword
      secretKeyRef:
        name: redis-secret
        key: redis-password
    - name: actorStateStore
      value: "true"
    - name: keyPrefix
      value: "insureportal"
    - name: ttlInSeconds
      value: "86400"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: insureportal-cache
  namespace: insureportal
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis:6379"
    - name: redisPassword
      secretKeyRef:
        name: redis-secret
        key: redis-password
    - name: keyPrefix
      value: "cache"
    - name: ttlInSeconds
      value: "300"
