apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "permify.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "permify.labels" . | nindent 4 }}
automountServiceAccountToken: false
