apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
automountServiceAccountToken: false
