apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: pos-insureportal
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    pod-security.kubernetes.io/enforce: baseline
